spring:
  application.name: exercise1-backend
  datasource:
    name: exercise1
    url: jdbc:mysql://localhost/exercise1?useSSL=false
    username: root
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
    hibernate.use-new-id-generator-mappings: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/00-master.xml

server:
  compression:
    enabled: true
    mime-types: application/json
  port: 9000
  http:
    port:
      8080

liquibase:

---
spring:
  profiles: local
  datasource:
    password: exercise1
